version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /var/dumps
      - ./db/setup-script/:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - rmg-network

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env
    networks:
      - rmg-network

  webapi-dev:
    image: rmg-webapi
    restart: always
    container_name: rmg-webapi-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5297:80
    networks:
      - rmg-network

networks:
  rmg-network:
    driver: bridge

