version: '3.8'

services:

  # webapi-dev:
  #   image: luis8h/rmg_webapi:dev
  #   restart: always
  #   container_name: rmg-webapi-container
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - 5297:80
  #
  db:
    image: postgres:latest
    restart: always
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /var/dumps
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env

