version: '3.8'

services:

  rmg_db_sta:
    image: postgres:latest
    restart: on-failure
    container_name: rmg_db_sta
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /var/dumps
      - ./db/sta-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - rmg-network-sta
    ports:
      - ${DB_PORT}:5432

  rmg_adminer_sta:
    image: adminer
    container_name: rmg_adminer_sta
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080
    env_file:
      - .env
    networks:
      - rmg-network-sta

  rmg_webapi_sta:
    image: luis8h/rmg_webapi:sta
    restart: on-failure
    container_name: rmg_webapi_sta
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - 5298:80
    networks:
      - rmg-network-sta

networks:
  rmg-network-sta:
    driver: bridge


